{% set name = "uncertainties" %}
{% set version = "3.1.2" %}
{% set sha256 = "ba07c17a8a78cb58a47cd373079c7ea459f8b26cd474e29163b6ba0d72856a1e" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/u/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - numpy
  imports:
    - {{ name }}
    - {{ name }}.unumpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD 3-Clause
  summary: 'Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.'

extra:
  recipe-maintainers:
    - ocefpaf
